<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Course\Course;
use App\Models\Instructor;
use App\Models\Course\CourseCategory;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $count = 20;

        $category = CourseCategory::where('slug', 'default')->first();
        $instructors = Instructor::all();

        if (!$category || $instructors->isEmpty()) {
            return;
        }

        for ($i = 1; $i <= $count; $i++) {
            $title = "Sample Course {$i}";

            Course::create([
                'title' => $title,
                'slug' => Str::slug($title . '-' . $i),
                'course_type' => 'recorded',
                'status' => 'approved',
                'level' => 'beginner',
                'short_description' => 'This is a sample course generated by seeder.',
                'description' => 'Detailed description for ' . $title . '. This course covers fundamental concepts and practical applications.',
                'language' => 'en',
                'pricing_type' => 'free',
                'price' => null,
                'discount' => false,
                'discount_price' => null,
                'drip_content' => false,
                'thumbnail' => null,
                'banner' => null,
                'preview' => null,
                'expiry_type' => 'lifetime',
                'expiry_duration' => null,
                'created_from' => 'web',
                'meta_title' => $title,
                'meta_keywords' => implode(',', array_slice(['course', 'learning', 'education', strtolower($title)], 0, 3)),
                'meta_description' => 'Learn ' . strtolower($title) . ' with our comprehensive online course.',
                'og_title' => $title,
                'og_description' => 'Join thousands of students learning ' . strtolower($title),
                'instructor_id' => $instructors->random()->id,
                'course_category_id' => $category->id,
                'course_category_child_id' => null,
            ]);
        }
    }
}
